version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - dupl
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - ireturn
    - lll
    - mnd
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
  settings:
    revive:
      rules:
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T,testing.TB"
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - dupl
          - err113
          - exhaustruct
          - forcetypeassert
          - gosec
          - maintidx
          - nilerr
          - paralleltest
          - wrapcheck
        path: _test\.go
      - linters:
          - forcetypeassert
          - wrapcheck
        path: internal/mocks/*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - localmodule
        - default
        - blank
        - dot
        - alias
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
