version: "3.6"

services:
  db:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: su
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
