// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePost(ctx context.Context, db DBTX, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, db DBTX, id uuid.UUID) (int64, error)
	GetPost(ctx context.Context, db DBTX, id uuid.UUID) (Post, error)
	ListPosts(ctx context.Context, db DBTX) ([]Post, error)
	UpdatePost(ctx context.Context, db DBTX, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
